--  Supabase SQL Editor to disable RLS on all ZTS tables
ALTER TABLE users DISABLE ROW LEVEL SECURITY;

ALTER TABLE departments DISABLE ROW LEVEL SECURITY;

ALTER TABLE devices DISABLE ROW LEVEL SECURITY;

ALTER TABLE sessions_log DISABLE ROW LEVEL SECURITY;

ALTER TABLE otp_store DISABLE ROW LEVEL SECURITY;

ALTER TABLE risk_logs DISABLE ROW LEVEL SECURITY;

ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;

ALTER TABLE ip_rules DISABLE ROW LEVEL SECURITY;