name: Deploy ZTS to VPS

on:
  push:
    branches:
      - main  # Whenever you push to the 'main' branch, this pipeline activates

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS and Run Deploy Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 212.227.39.216
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/zts-web
            bash deploy.sh
